# Generated by Django 4.2.30 on 2026-06-01 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_classschedule_assigned_sub_educator"),
        ("live_classes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="livesession",
            name="schedule",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="live_session",
                to="scheduling.classschedule",
            ),
        ),
    ]
