# Generated by Django 4.2.30 on 2026-05-13 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Target category. Leave blank for all students.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.category",
            ),
        ),
    ]
