# Generated by Django 4.2.30 on 2026-05-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_assigned_educator"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Only admin can feature a course on the home page",
            ),
        ),
    ]
