# Generated by Django 4.2.30 on 2026-06-07 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0003_add_is_featured_to_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="assigned_sub_educators",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "educator"},
                related_name="assigned_subjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
