# Generated by Django 4.2.30 on 2026-06-01 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classschedule",
            name="assigned_sub_educator",
            field=models.ForeignKey(
                blank=True,
                help_text="Sub-educator assigned to conduct this class",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
