# Generated by Django 4.2.30 on 2026-06-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_classschedule_assigned_sub_educator"),
    ]

    operations = [
        migrations.AddField(
            model_name="classschedule",
            name="topics_covered",
            field=models.TextField(
                blank=True,
                help_text="Topics or course content to be covered in this live class",
            ),
        ),
    ]
