# Generated by Django 4.2.30 on 2026-06-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_module_assigned_sub_educators"),
        ("scheduling", "0003_classschedule_topics_covered"),
    ]

    operations = [
        migrations.AddField(
            model_name="classschedule",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="courses.module",
            ),
        ),
    ]
