# Generated by Django 4.2.30 on 2026-05-13 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("authentication", "0002_follower"),
    ]

    operations = [
        migrations.AddField(
            model_name="educatorprofile",
            name="institute_details",
            field=models.TextField(
                blank=True, help_text="Details about your institute"
            ),
        ),
        migrations.AddField(
            model_name="educatorprofile",
            name="institute_name",
            field=models.CharField(
                blank=True,
                help_text="Name of your coaching center or institute",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="selected_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="courses.category",
            ),
        ),
    ]
