# Generated by Django 4.2.30 on 2026-05-13 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("authentication", "0003_educatorprofile_institute_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="educatorprofile",
            name="primary_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="educators",
                to="courses.category",
            ),
        ),
    ]
