# Generated by Django 4.2.30 on 2026-05-15 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_educatorprofile_primary_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="educatorprofile",
            name="parent_institute",
            field=models.ForeignKey(
                blank=True,
                help_text="The institute that created this educator account",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_educators",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
