# Generated by Django 4.2.30 on 2026-05-17 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_educatorprofile_parent_institute"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="linked_educator",
            field=models.ForeignKey(
                blank=True,
                help_text="Educator linked via promo code",
                limit_choices_to={"role": "educator"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_promos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "educator",
                    models.OneToOneField(
                        limit_choices_to={"role": "educator"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_code_obj",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
