# Generated by Django 4.2.30 on 2026-05-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_user_linked_educator_promocode"),
    ]

    operations = [
        migrations.AddField(
            model_name="educatorprofile",
            name="educator_type",
            field=models.CharField(
                choices=[
                    ("individual", "Individual Educator"),
                    ("institute", "Institute"),
                ],
                default="individual",
                max_length=20,
            ),
        ),
    ]
